### ISSUE TITLE
One definition missing

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-pages-docs#52]
[Enter feedback here]
The article is missing definition for 'Parent' Access Type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Version Independent ID: e5dd7334-1124-4cb2-322a-79a6735d5852
* Content: [Configuring table permissions in Power Pages](https://learn.microsoft.com/en-us/power-pages/security/table-permissions)
* Content Source: [power-pages-docs/security/table-permissions.md](https://github.com/MicrosoftDocs/power-pages-docs/blob/main/power-pages-docs/security/table-permissions.md)
* Service: **power-pages**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback. Can you provide further clarification? There is no ‘parent’ access type (only global, account, contact, and self).

Are you referring to the table permission of which you create child permissions from (as described here: [Configure child permissions](https://learn.microsoft.com/power-pages/security/table-permissions#configure-child-permissions))? 

That table permission would be considered the ‘parent’ table permission, but its typically something not created implicitly, where you can create child permissions.

**Comment by nickdoelman** [comment]
Thank you for the clarification! Yes, this option is available using the Portal Management App, but not available using the Design studio.

We do call this out in a note in our documentation: [Available access types](https://learn.microsoft.com/power-pages/security/table-permissions#available-access-types)

_The Parent access type is only available in the Portal Management app. Instead of creating a table permission with the access type of Parent when using the design studio, directly add child permission to existing table permissions._
